### ISSUE TITLE
Act 2 Minor Issues

### ISSUE THREAD

**Issue by asmoranomar** [plasticmacaroni/bg3-missables#11]
Mason's Guild
This has two sections.  Would be irrelevant, but it interferes with the expand/collapse function of the guide, and clicking on the second one only expand/collapses the first one.  I don't know if having two entries was intentional (Mason's Guild vs Mason's Guild Basement?) but either way it doesn't play nice.

Destroyed Town
Formatting isn't playing nice with the links.  Could probably do without the ()'s.  Additionally, there is a warning about proceeding that I cannot find a reference for anywhere else.  Do you have a source for this? I'm only aware of the lockout for entering Shadowfell. (see the bolded section near the bottom of https://bg3.wiki/wiki/Gauntlet_of_Shar)

Ketheric
What is this?  I would assume the 'basement of the prison' is the Oubliette, but this section is already covered by 'Below Moonrise Towers'

Request
I also have a slight recommendation: If the guide is going to be concise and non-spoiler, then it should have links to the wiki (or another resource) for **every** entry.  It's minor, but I've confused a few things that I thought was being referenced at times simply because I had a different experience in my previous play-thru.  I also suspect the issue above (lockout warning) might have been misattributed, but now with no source/links and it's vagueness, I cannot determine if it's a mistake or not.  I could probably contribute to this effort, but my design ideas might not match yours and I didn't want to start submitting random PR's.

**Comment by plasticmacaroni** [comment]
This is great feedback! These are some sweeping changes, but I think they're good ones.

**Comment by plasticmacaroni** [comment]
It's definitely not perfect, but I've incorporated a lot of your feedback in the latest two commits. See the newest one in https://github.com/plasticmacaroni/bg3-missables/commit/ed009ed1f4f0b2a3f59d1d062d23a845e1b6c78b

**Comment by plasticmacaroni** [comment]
Last thought -- feel 100% free to make commits. My vision for this is that it's straightforward, spoiler-free, and useful. It's mostly been thanks to the community already!

**Comment by asmoranomar** [comment]
How does something like this look?
https://i.imgur.com/cipx50M.png
https://i.imgur.com/Cc6KCPY.png

**Comment by plasticmacaroni** [comment]
I love the introduction of the graduation cap! The key looks beautiful.

For the second image, I'd prefer something in the sentence itself be highlighted (my thought process is that any sentence that can't have a highlight is either not on bg3.wiki or shouldn't be included).

That being said, I'll defer to what you want to see here, if you're submitting PRs. I'm a big believer in community development of this, since this originally came from a community project for DS2 and a community checklist for BG3!

**Comment by plasticmacaroni** [comment]
Wow, super thorough.

If you add a unique symbol to items, I have another checklist already with logic for filtering them out as the user wants. (https://github.com/plasticmacaroni/dark-souls-2-sotfs-cheat-sheet)

I can absolutely add filters for unique items that the player may want to track or un-track, if you'd like to include these. 

At the end of the day, even without a filter, I think this is something most folks would want to see!

**Comment by asmoranomar** [comment]
I'm having a hard time visualizing how it would work.  Certainly having a separate checklist for items is nice, but it would need to be organized to follow the walkthrough or the walkthrough would need to reference the item in the checklist.  At that point, I feel like 'why not just put it in the walkthrough?'.  Basically, an interface design issue.  There are over 3000 items in the game, it's going to be very hard to organize them in a way outside the walkthrough so that someone doesn't forget to command drop the first devil in the game.  I'm only able to work with a spreadsheet now because I can sort and filter dynamically; and unless I'm mistaken, we can't do that here.

But ultimately I think the focus should be on the walkthrough and define what 'missable' means in the context of items, and work from there.

**Comment by plasticmacaroni** [comment]
Updated the README to say a big thanks for the contributions here!
https://github.com/plasticmacaroni/bg3-missables/blob/main/README.md
