### ISSUE TITLE
+1 Breastplate

### ISSUE THREAD

**Issue by asmoranomar** [plasticmacaroni/bg3-missables#22]
Note for myself once the walkthrough is updated.

Due to the filter import, the +1 Breastplate was excluded due to being flagged as an ordinary item. Ordinary items are items that are unique, but otherwise identical to more accessible items. In this instance, the +1 Breastplate is the same as a Breastplate. It can be obtained from Akabi in Circus of the Last Days in Act 3 as a consolation prize for playing Wheel of Fortune.

Question: Should this item be added to the guide?

**Comment by plasticmacaroni** [comment]
Updated the walkthrough! Just had to get to the weekend to help test and merge. Thanks again!
