### ISSUE TITLE
Colony 

### ISSUE THREAD

**Issue by 122abc123** [plasticmacaroni/bg3-missables#5]
- the brain machine, there are two brains you can get prior to going down (Dark and Slave), since you are locked out/in and basically only have what you go in with, imagine it is often overlooked as you would have needed to collect these two brains prior and carried them with you this whole time (they are each 5kg)

However they have dialog most will have missed, not sure its worth including in your list, as far as I can tell you only get dialog (and you do not get to interact with them, they say their lines than convo ends, one a creepy song, the other panic)

but thought I would throw this in, since it is likely something many have missed

**Comment by plasticmacaroni** [comment]
Great point! Added in https://github.com/plasticmacaroni/bg3-missables/commit/fa0965a1a9607f9b1ae9e1c57d684ace9a663f39
